/*
This is the C configuration file for the keymap

  Copyright 2022 Mark Stosberg (@markstos)
  SPDX-License-Identifier: GPL-2.0-or-later

*/

#pragma once

#define SPLIT_WPM_ENABLE
#define OLED_TIMEOUT 60000
#define SPLIT_TRANSPORT_MIRROR
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_RIVERFLOW
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
