CONVERT_TO=liatris
ENCODER_ENABLE=false
RGBLIGHT_ENABLE=true
BACKLIGHT_ENABLE=true
WPM_ENABLE = yes

DEBOUNCE_TYPE = asym_eager_defer_pk

MOUSEKEY_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
# TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
# COMBO_ENABLE = yes
